# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install dependencies
WORKDIR /app
COPY package.json package-lock.json* yarn.lock* ./
RUN npm install --omit=dev

# Copy source code
COPY . .

# Expose port if HTTP mode used
EXPOSE 3334

# Default command (can be overridden by MCP host with stdio args)
CMD ["node", "src/index.mjs", "--stdio", "--feishu-app-id", "${FEISHU_APP_ID}", "--feishu-app-secret", "${FEISHU_APP_SECRET}"]
